baseurl = "http://mismith0227.github.io/"
languageCode = "ja"
title = "pickles"

[Params]
site_name = "pickles"
description = "つけものブログ"
twitter = "https://twitter.com/misumi_takuma"
github = "https://github.com/mismith0227"
