baseurl = "http://mismith0227.github.io/"
languageCode = "ja"
title = "pickles"

[Params]
site_name = "pickles"
description = "つけものブログ"
twitter_account = "misumi_takuma"
github = "https://github.com/mismith0227"
analytics = "UA-51630362-4"
