baseurl = "http://mismith0227.github.io/"
languageCode = "ja"
title = "pickles"

[Params]
site_name = "title"
description = "description"
twitter_account = "twitter"
github_account = "github"
analytics = "UA-12345678-9"

[permalinks]
pages = "/:slug/"
