author = "Takuma Misumi"
description = "Pickles is a modern, simple and beautiful Hugo theme"
license = "MIT"
name = "Pickles"
source_repo = "git@github.com:mismith0227/hugo_theme_pickles.git"
tags = ["Responsive", "Blog", "Google analytics", "Disqus", "Clean", "Tags", "Minimal", "Minimalist", "Simple", "White", "Starter"]
